# Generated by Django 3.2.5 on 2021-11-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_list_item',
            name='time_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
